### ISSUE TITLE
Verify Image Signatures: TypeError: Cannot create property 'owner' on string

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#259]
### Current Behavior

Add button breaks if I change signature type field when creating new Verify Image Signatures policy

[Screencast from 2023-02-23 10-52-22.webm](https://user-images.githubusercontent.com/538604/220873947-0cc2e260-7ef4-487e-b277-9266b40455c7.webm)

```
console.js:31 TypeError: Cannot create property 'owner' on string ''
    at f.parseSequenceSubquestion (SequenceTree.vue:159:1)
    at SequenceTree.vue?1183:1:1092
    at f.Ce [as _l] (vue.runtime.esm.js:2646:16)
    at SequenceTree.vue?1183:1:826
    at f.Ce [as _l] (vue.runtime.esm.js:2646:16)
    at SequenceTree.vue?1183:1:276
    at f.Ce [as _l] (vue.runtime.esm.js:2646:16)
    at f.Oe (SequenceTree.vue?1183:1:165)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
```

**Comment by jordojordo** [comment]
This should be fixed with https://github.com/kubewarden/ui/pull/260, will need to test with `1.0.3-rc2`

**Comment by kravciak** [comment]
Fixed, thanks
